[gwern]
title = "Gwern Branwen"
url = "https://www.gwern.net/"
entrySelector = "#newest li"
titleSelector = "a"
linkSelector = "a"

[jtunney]
title = "Justine Tunney"
url = "http://justine.lol"
entrySelector = "td + td ul:first-of-type li"
titleSelector = "a"
linkSelector = "a"
# filters = ["<small>"]
